{% set name = "gym-saturation" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7308e6b3e1a9d8fedf58faf148d5775e4f8b885ac3b1230b4c9cc572dfb35876

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - gymnasium <1.0.0
    - importlib_resources
    - pexpect

test:
  imports:
    - gym_saturation
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - gym_saturation
  commands:
    - pip check
    - >
      pytest --doctest-modules --ignore=gym_saturation/vampire_wrapper.py --ignore=gym_saturation/envs --ignore=gym_saturation/wrappers gym_saturation

about:
  home: https://github.com/inpefess/gym-saturation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: a collection of Gymnasium environments for saturation provers
  description: |
    gym-saturation is collection of Gymnasium environments for guiding
    automated theorem provers by reinforcement learning agents.
  doc_url: https://gym-saturation.readthedocs.io/
  dev_url: https://github.com/inpefess/gym-saturation

extra:
  recipe-maintainers:
    - inpefess
