{% set name = "gym-saturation" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28f7ed7b5fa4581ff9d0e1289b0c3cd57359668bf4bb23b10c310eaf4e64d88a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - gym
    - lark-parser
    - importlib_resources
    - orjson

test:
  imports:
    - gym_saturation
  requires:
    - pip
    - pytest
  source_files:
    - gym_saturation
  commands:
    - pip check
    - pytest --doctest-modules gym_saturation

about:
  home: https://github.com/inpefess/gym-saturation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: an OpenAI Gym environment for saturation provers
  description: |
    gym-saturation is an OpenAI Gym environment for reinforcement learning
    agents striving to prove theorems.
  doc_url: https://gym-saturation.readthedocs.io/
  dev_url: https://github.com/inpefess/gym-saturation

extra:
  recipe-maintainers:
    - inpefess
