{% set name = "gym-saturation" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae29a1b210c027d94a0d91e5282ad898c219997b42fd1173a09478c8785d4098

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - gym
    - lark-parser
    - importlib_resources
    - orjson
    - pexpect

test:
  imports:
    - gym_saturation
  requires:
    - pip
    - pytest
  source_files:
    - gym_saturation
  commands:
    - pip check
    - pytest --doctest-modules --ignore=gym_saturation/vampire_wrapper.py --ignore=gym_saturation/agent_testing.py gym_saturation

about:
  home: https://github.com/inpefess/gym-saturation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: an OpenAI Gym environment for saturation provers
  description: |
    gym-saturation is an OpenAI Gym environment for reinforcement learning
    agents striving to prove theorems.
  doc_url: https://gym-saturation.readthedocs.io/
  dev_url: https://github.com/inpefess/gym-saturation

extra:
  recipe-maintainers:
    - inpefess
