{% set name = "gym-saturation" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 43332f438b2d9a8564901290b0ee8aae7f04fb999435fa974a4d1aeddafc531c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8, <3.13
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8, <3.13
    - gymnasium <1.0.0
    - importlib_resources
    - pexpect

test:
  imports:
    - gym_saturation
  requires:
    - pip
    - pytest
  source_files:
    - gym_saturation
  commands:
    - pip check
    - >
      pytest --doctest-modules --ignore=gym_saturation/vampire_wrapper.py --ignore=gym_saturation/envs --ignore=gym_saturation/wrappers gym_saturation

about:
  home: https://github.com/inpefess/gym-saturation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: a collection of Gymnasium environments for saturation provers
  description: |
    gym-saturation is collection of Gymnasium environments for guiding
    automated theorem provers by reinforcement learning agents.
  doc_url: https://gym-saturation.readthedocs.io/
  dev_url: https://github.com/inpefess/gym-saturation

extra:
  recipe-maintainers:
    - inpefess
