{% set name = "gym-saturation" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 84ae56ad7320ae6b4a9e656181852d884d02e92bf8704a0bb8e6b2a57204383a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - gymnasium
    - importlib_resources
    - pexpect

test:
  imports:
    - gym_saturation
  requires:
    - pip
    - pytest
  source_files:
    - gym_saturation
  commands:
    - pip check
    - >
      pytest --doctest-modules --ignore=gym_saturation/vampire_wrapper.py --ignore=gym_saturation/agent_testing.py --ignore=gym_saturation/envs/vampire_env.py --ignore=gym_saturation/envs/iprover_env.py --ignore=gym_saturation/wrappers/age_weight_bandit.py --ignore=gym_saturation/wrappers/ast2vec_wrapper.py --ignore=gym_saturation/wrappers/parametric_actions_wrapper.py
      --ignore=gym_saturation/wrappers/duplicate_key_obs.py gym_saturation

about:
  home: https://github.com/inpefess/gym-saturation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: a collection of Gymnasium environments for saturation provers
  description: |
    gym-saturation is collection of Gymnasium environments for guiding
    automated theorem provers by reinforcement learning agents.
  doc_url: https://gym-saturation.readthedocs.io/
  dev_url: https://github.com/inpefess/gym-saturation

extra:
  recipe-maintainers:
    - inpefess
